kendryte/nncase

src/importer/onnx/onnx_importer.cpp
src/importer/onnx/onnx_importer.h
src/importer/onnx/ops/constant.cpp
src/importer/onnx/ops/conv.cpp
src/importer/onnx/ops/pad.cpp
src/importer/onnx/ops/pool.cpp
src/importer/onnx/ops/reshape.cpp
src/importer/onnx/ops/resize.cpp
src/importer/onnx/ops/slice.cpp

Following the discussion at #103 I've found and fixed several constructions with great UB potential in the Protobuf accessing methods. The initial code was too optimistic about using both the internal and provided structures of Protobuf objects without deep copy, still in most cases there were no lifetime guarantees, hence the subtle bugs were about to come. Now it's probably a little slower, but more stable, and as that's just importing of the model, not the inference, it's probably the right balance here. Could you please look it through and consider the merge?

ONNX: undefined behaviour fixes in ONNX importer

---

src/nncase/compiler.cpp

Started my experiments with the freshly refactored version of nncase and ONNX import in particular and found, that the DOT dump of the graph is now dropped with `--dump-ir` key is on, still the code of the output is still there and quite fine. Maybe I miss something, but here's a little edition to enable it again for the moment after the import phase.

Maybe bring back dot dump of the graph after importing

---

src/importer/onnx/ops/pad.cpp
tests/importer/onnx/basic/test_pad.py

Its data type is `int64` as per documentation (https://github.com/onnx/onnx/blob/master/docs/Changelog.md#pad-13), rather than `float`, which currently leads to extraction failure and assertion failure during the import.

onnx: fix `pad` input data type for `Pad` op

---

tests/importer/onnx/basic/test_pad.py

Following the test cases added in #304 I looked into it a little bit more and felt necessary to exclude the reduntant part of the test cases used to appear due to doubled pairs of parameters generated for opset version 2, which don't really change anything and perform literally the same test twice. Just not to waste computation power :)

onnx: change permutation of opset and version formats for `Pad` test

---

src/targets/neutral_target.cpp

remove fold pad+maxpool from nncase since neutral target does not support count_include_pad=true

remove fold_pad_maxpool from nncase

---

tests/test_runner.py

fix pytest when multiple inputs have different type

fix pytest when multiple inputs have different type

---

include/nncase/transforms/neutral/optimize_allocation.h
src/nncase/compiler.cpp
src/transforms/neutral/optimize_allocation.cpp
tests/schedule/buffer_fusion/test_bitcast.py

fix bitcast buffer allocation

---

Directory.Packages.props
src/Nncase.Core/IR/TypePattern.cs
src/Nncase.Core/Transform/Mutators/ConvertBlocksToOpaque.cs
src/Nncase.Core/Transform/Mutators/FlattenBuffer.cs
src/Nncase.Core/Transform/Mutators/FlattenSequential.cs
src/Nncase.Core/Transform/Mutators/FoldConstTuple.cs
src/Nncase.Core/Transform/Mutators/FoldIfThen.cs
src/Nncase.Core/Transform/Mutators/FoldLet.cs
src/Nncase.Core/Transform/Mutators/FoldMathCall.cs
src/Nncase.Core/Transform/Mutators/LowerBlockInit.cs
src/Nncase.Core/Transform/Mutators/RemoveNop.cs
src/Nncase.Core/Transform/Mutators/SubstituteVarAndCollectOpaqueBlock.cs
src/Nncase.Core/Transform/Mutators/Substitutor.cs
src/Nncase.Core/Transform/Mutators/UnFoldBlock.cs
src/Nncase.Core/Transform/Mutators/UnrollLoop.cs
src/Nncase.Core/Transform/PrimFuncPass.cs
src/Nncase.Core/Transform/RulesPass.cs
src/Nncase.Tests.TestFixture/TestingServices.cs
src/Nncase.Tests.TestFixture/TransformTestBase.cs

- Add mutators to `PrimFuncPass` need types of mutators. It requires to make mutators public.
- Allow `IsPointer` pattern accept all types (before `PrimType` only)

Make mutators public

---

src/Nncase.Compiler/Compiler.cs
src/Nncase.Core/Diagnostics/DumpScope.cs
src/Nncase.Core/Diagnostics/IDumpper.cs
src/Nncase.Core/Diagnostics/NullDumpper.cs
src/Nncase.Core/IR/Math/Clamp.cs
src/Nncase.Core/IR/Random/Normal.cs
src/Nncase.Core/PatternMatch/ExprPattern.cs
src/Nncase.Core/Transform/PassManager.cs
src/Nncase.Diagnostics/Diagnostics/Dumpper.cs
src/Nncase.EGraph/Transform/EGraphExtractor.cs
src/Nncase.EGraph/Transform/EGraphPrinter.cs
src/Nncase.Evaluator/EvaluateVisitor.cs
src/Nncase.Evaluator/Math/Clamp.cs
src/Nncase.Importer/BaseImporter.cs
src/Nncase.Tests/Diagnostics/UnitTestDumpper.cs
src/Nncase.Tests/Evaluator/UnitTestEvaluatorMath.cs
src/Nncase.Tests/Rewrite/RewriteBase.cs
src/Nncase.Tests/Rewrite/UnitTestDataFlowRewrite.cs
src/Nncase.Tests/Rewrite/UnitTestDataFlowRewriteFactory.cs
src/Nncase.Tests/Rewrite/UnitTestEGraphRewrite.cs
src/Nncase.Tests/Rewrite/UnitTestEGraphRewriteFactory.cs
src/Nncase.Tests/Rules/Neutral/UnitTestCombineBinary.cs
src/Nncase.Tests/Rules/Neutral/UnitTestCombineTranspose.cs
src/Nncase.Tests/Rules/Neutral/UnitTestFoldConv2DMulAdd.cs
src/Nncase.Tests/Rules/Neutral/UnitTestReluToClamp.cs
src/Nncase.Transform/Rules/Neutral/CombineBinary.cs
src/Nncase.Transform/Rules/Neutral/CombineTranspose.cs
src/Nncase.Transform/Rules/Neutral/FoldConv2DMulAdd.cs
src/Nncase.Transform/Rules/Neutral/ReluToClamp.cs
tools/stackvm_gen/IsaGen/Program.cs

```csharp
// Can custom dump information in the tests.
using (var _ = new DumpScope($"Eval", DumpFlags.Evaluator)){
CompilerServices.Evaluate(expr);
}
```
I suggest to name CombineRule according to the order of Call. For example:
`Transpose(Pad(x)) => Pad(Transpose(x))`, should be named `CombineTransposePad`.

Add Fold Conv2D+BatchNormal

---

src/Nncase.Compiler/Compiler.cs
src/Nncase.EGraph/CostModel/EGraphCostEvaluator.cs
src/Nncase.Tests/Rewrite/UnitTestEGraphRewrite.cs
src/Nncase.Transform/Rules/Neutral/FuseClampConv2D.cs

The EGraph cost evaluator marker cost getter will return `Costs.Zero`, it will affect the accumulation of cost.
Eg. we fuse the `FakeActivations` and `Relu`, but the `Relu` cost equal to fused `FakeActivations`, finally the non-optimal graph will be extracted.
when fix the marker cost getter, it can extract the optimal graph.

Fix egraph marker cost evaluator

---

src/Nncase.Compiler/Compiler.cs
src/Nncase.Core/IR/Tuple.cs
src/Nncase.EGraph/CostModel/EGraphCostPrinter.cs
src/Nncase.Tests/Rules/Neutral/UnitTestAddMarker.cs
src/Nncase.Transform/Rules/Neutral/AddRangeOfAndMarker.cs

1. fix function body no rangeof marker.
when the call inputs added the marker, the AddRangeOfMarker Rule can't match. So we can't add marker on the function body.
```il
%337 = %336@(RangeOf = const(f32[2] : {-23.41534,19.147308})): // f32[1,7,7,2048]
%338 = Relu(%337): // f32[1,7,7,2048] the relu inputs has marker.
%339 = (%338): // (f32[1,7,7,2048])
```

fix function body add marker

---

src/Nncase.Core/Transform/PassManager.cs
src/Nncase.Core/Transform/PrimFuncPass.cs

we don't need dump whole module in once rewrite.
```csharp
if (!object.ReferenceEquals(pre, post))
{
if (_dummper.IsEnabled(DumpFlags.PassIR))
{
// _dummper.DumpModule(pre, string.Empty, $"{passIndex}_{pass.Name}/Before");
_dummper.DumpIR(pre, string.Empty, $"{passIndex}_{pass.Name}/Before");
}
}
```

Only dump function which  mutated.

---

src/Native/src/kernels/stackvm/reference/activation.cpp
src/Nncase.Core/Transform/Mutators/UnRollLoopSequential.cs
src/Nncase.Tests/Rewrite/UnitTestEGraphRewrite.cs

1. use cached const parameters to speed up the next evaluation
2. add egraph CSE test case

speed up unroll evaluate

---

src/Native/src/runtime/stackvm/evaluate_stack.cpp

1.  nds not support `-Wclass-memaccess`

Fix k510 runtime build

---

src/Nncase.Core/CostModel/Cost.cs
src/Nncase.Core/LinqExtensions.cs
src/Nncase.Evaluator/Math/MatMul.cs
src/Nncase.Evaluator/Math/Quantize.cs
src/Nncase.Evaluator/Math/Reduce.cs
src/Nncase.Evaluator/Math/ReduceArg.cs
src/Nncase.Evaluator/NN/Activations.cs
src/Nncase.Evaluator/NN/Conv2D.cs
src/Nncase.Evaluator/NN/Conv2DTranspose.cs
src/Nncase.Evaluator/NN/Hardmax.cs
src/Nncase.Evaluator/NN/ReduceWindow2D.cs
src/Nncase.Evaluator/NN/Softmax.cs
src/Nncase.Evaluator/RNN/LSTM.cs
src/Nncase.Tests/Core/UnitTestCost.cs

1. when using double as cost value type:
c0 = { [MemoryLoad, 1651643172136040] [MemoryStore, 953885239498522] [CPUCycles, 13437180688291688] }
c1 = { [CPUCycles, 1] }
the `c0` will equal `c1 + c0`

Fix EGraph Cost accumulate bug

---

docs/USAGE_EN.md
docs/USAGE_ZH.md
examples/user_guide/README.md
examples/user_guide/k210_simulate.ipynb
examples/user_guide/nncase_base_func.py
examples/user_guide/simulate.ipynb
tests/importer/onnx_/basic/test_slice.py

1. add k210 pipeline docs in USAGE.md
2. add simulate.ipynb for compile and inference

GNNE-1886 210_docs and script

---

src/Nncase.Core/Utilities/ReplaceUtility.cs
src/Nncase.Passes/Rules/Lower/BroadcastMarker.cs
src/Nncase.Tests/Rules/UnitTestBroadcastMarker.cs

add broadcast marker for do TargetIndependent after assign range in ShapeBucket.

Broadcast marker

---

tests/ci_proxy.py
tests/config.toml
tests/nuc_proxy.py
tests/test_runner.py

- Disable dump_hist by default which takes a long time.
- Remove TelnetLib to reboot evb as netcard may doesn't work, use serial instead.
- nuc_proxy returns 1024 bytes of exception at most to avoid overflow.
- Add more debug log for ci_proxy and nuc_proxy to profiling.

Improve test runner.

---

tests/nuc_proxy.py

- serial 0: login first, then reboot
- serial 1: enter directly to exit from default face_detect.

Fix the exceptions for both serial 0 and 1.

---

tests/config.toml
tests/inference.py
tests/nuc_proxy.py
tests/test_runner.py
tests/test_utils.py

- support dynamic model test on evb.
- config dump file in config.toml

Test runner supports dynamic shape model running on evb.

---

tests/config.toml
tests/inference.py
tests/json2md.py
tests/nuc_proxy.py
tests/test_runner.py
tests/test_utils.py
tests/update_trace_info.py

- Add infer_report_opt into config.toml
- test_runner gets more benchmark test items
- nuc_proxy: return all result from evb and fix exceptions.
- json2md:  support one or more json file as input, convert json into htm table instead of pandoc
- Add update_trace_info.py, which is modified from qihang.

Add more benchmark test items to show.

---

python/nncase/__init__.py
tests/compare_util.py
tests/inference.py
tests/ncnn_test_runner.py
tests/test_runner.py
tests/tflite_test_runner.py

- Extract actual fps only for dynamic model
- Fix tflite test runner to run dynamic model

Fix benchmark test flow with dynamic shape.

---

docs/MixQuant.md
docs/USAGE_v2.md
docs/USAGE_v2_EN.md
examples/user_guide/k230_simulate-EN.ipynb
examples/user_guide/k230_simulate-ZH.ipynb
python/nncase/__init__.py
python/nncase/native/ffi.cpp
src/Native/include/nncase/compiler.h
src/Nncase.Compiler/Interop/CApi.cs
src/Nncase.Importer/TFLite/MatMul.cs
tests/config.toml

1. add quant scheme strict mode to config.toml

GNNE-1714:Feature/add quant strict mode to config

---

src/Nncase.Compiler/Compiler.cs

shutdown FoldPrePostReshapeSoftmax transform, the conditions are not strict enough, it will cause damage to other scenes.

GNNE-1714:shutdown FoldPrePostReshapeSoftmax transform

---

src/Nncase.Passes/Rules/Neutral/AddPreProcess.cs

1，Add the name of the OP related to Norm, otherwise there will be problems using json to guide quantification.

GNNE-1714:add norm op name

---

src/Nncase.Core/IR/Expr.cs
src/Nncase.Core/Utilities/DistributedUtility.cs

1. support non-uniform sharding

GNNE-1974: Feature/non uniform

---

src/Nncase.Passes/Rules/Neutral/FoldDilatedConv2D.cs
src/Nncase.Passes/Rules/Neutral/SwapBinaryArgs.cs
src/Nncase.Passes/Rules/WithMarker/CombineTranspose.cs

fix metadata for FoldDilatedConv2D, SwapBinaryArgs, CombineTranspose

Fix metadata

---

src/Nncase.Compiler/Compiler.cs
src/Nncase.Core/ICompiler.cs
src/Nncase.Studio/Util/CompileConfig.cs
src/Nncase.Studio/Util/DataUtil.cs
src/Nncase.Studio/ViewModels/CompileViewModel.cs

fix studio CheckViewModel and progress bar

Fix Studio

---

src/Nncase.Evaluator/Tensors/Reshape.cs

fix reshape for NotImplementedException

Fix Reshape

---

src/Nncase.EGraph/Passes/EGraphExtractors/SatExtractor.cs

1, Adjust the number of processors used for egraph search to half of the total number of processors.

GNNE-1714:adjust for processor counter

---

src/Nncase.EGraph/Passes/EGraphExtractors/SatExtractor.cs
src/Nncase.Passes/Rules/Neutral/AddRangeOfAndMarker.cs

1，Modify the naming rules of LSTM GetItem；
2，Modify egraph search time to prevent deadlock。

GNNE-1714:Fix/search time egraph

---

src/Nncase.Passes/Rules/Neutral/CombineQuantize.cs

1. replace != with !ReferenceEquals in CombineQuantizeConcat

Fix Not Equal

---

src/Nncase.Compiler/Compiler.cs
src/Nncase.Evaluator/NN/Activations.cs
src/Nncase.Importer/Onnx/Transpose.cs
src/Nncase.Importer/TFLite/SpaceToBatchND.cs
src/Nncase.Passes/Rules/Neutral/FoldDilatedConv2D.cs
src/Nncase.Passes/Rules/ShapeBucket/RecordFusionShape.cs
src/Nncase.Passes/Rules/ShapeBucket/ShapeBucket.cs
src/Nncase.Passes/Rules/ShapeBucket/ShapeBucketHelper.cs
src/Nncase.Passes/Rules/WithMarker/CombineReshapePad.cs
tests/importer/onnx_/basic/test_transpose.py

1. fix s2b b2s importer
2. fix ShouldBeRestore
3. fix bucket pipeline
4. add swish ShapeEvaluator
5. add some marker rule

Fix Bucket

---

src/Nncase.Compiler/Compiler.cs
src/Nncase.Core/PatternMatch/PatternUtility.cs
src/Nncase.Passes/Rules/WithMarker/CombineReshapePad.cs

1. match more marker for marker rule
2. fix conflict between two CombineTransposePad when shapebucket

Fix Melgan

---

src/Nncase.Compiler/Compiler.cs
src/Nncase.Core/IR/NN/Functional.cs
src/Nncase.Core/IR/NN/LayerNorm.cs
src/Nncase.Passes/Rules/Neutral/FoldLayerNorm.cs

convert channel first to channel last

support layernorm channel first(C#)

---

src/Native/include/nncase/runtime/interpreter.h
src/Native/src/runtime/cpu/loaders/elf/elf_loader.cpp
src/Native/src/runtime/cpu/loaders/elf/elf_loader.h
src/Native/src/runtime/cpu/loaders/macho/macho_loader.cpp
src/Native/src/runtime/cpu/loaders/macho/macho_loader.h
src/Native/src/runtime/cpu/loaders/pe/pe_loader.cpp
src/Native/src/runtime/cpu/loaders/pe/pe_loader.h
src/Native/src/runtime/cpu/runtime_function.cpp
src/Native/src/runtime/cpu/runtime_function.h
src/Native/src/runtime/cpu/runtime_module.cpp
src/Native/src/runtime/cpu/runtime_module.h
src/Native/src/test_cli.cpp

[feat] Support load cpu module from external path
