README.md
add dependencies for compiling nncase
=> add dependencies

src/cli/cli.cpp
i fixed cli argument parsing so now it works
=> fix cli arguments parsing

README.md
Could you please update the link to my blog in the Resources section of README.md?
=> The URL for the Shts's Blog has been updated.

include/nncase/compiler.h, src/nncase/compiler.cpp, tests/test_util.py
add default input_type in test_util  and  support it in compiler.cpp 
add optimize_target_dependent type condition for ptq
=> fix test_util for pytest

include/nncase/ir/quantizer.h, src/evaluator/quantizer.cpp
add another KLD quantization method
=> another kld quant method

src/importer/onnx/ops/batchnorm.cpp, src/importer/onnx/ops/resize.cpp, tests/importer/onnx/basic/test_softmax.py, tests/importer/tflite/combine/test_conv2d_act.py, tests/test_runner.py
1. Fix resize scale/size among different opset version(10, 11, 13)
2. Fix potential empty attribute of batchnorm
3. Fix softmax onnx test case
4. Record test reuslt into test_result.txt when unit test finished
=> Fix some onnx importer issues.

cmake/Modules/FindOpenMP.cmake
=> add cmake version

cmake/nncaseruntimeConfig.cmake.in
add nncaseruntime package dependency export
=> fix nncaseruntime config export

tests/importer/onnx/basic/test_binary.py
=> update binary pytest of onnx

include/nncase/targets/target.h, src/nncase/compiler.cpp, src/targets/target.cpp
=> convert copy to gnne_load+gnne_store after buffer fusion

include/nncase/transforms/neutral/space_to_batch_transform.h, src/targets/neutral_target.cpp, src/transforms/neutral/CMakeLists.txt, src/transforms/neutral/space_to_batch_transform.cpp
=> convert space2batch to pad

tests/onnx_test_runner.py
=> Set static shape for onnx models with dynamic shape.

tests/compare_util.py, tests/config.yml, tests/importer/onnx/basic/test_unary.py, tests/importer/tflite/model/test_densenet.py, tests/importer/tflite/model/test_mobilenetv1.py, tests/importer/tflite/model/test_mobilenetv2.py, tests/importer/tflite/model/test_resnet50.py, tests/importer/tflite/model/test_resnet50v2.py, tests/test_runner.py
1. support more compare method
2. allow configure multi target compare method:
the `specifics` block can set specific target by match condition
```python
overwrite_cfg = """
judge:
specifics:
- matchs: 
target: k210
ptq: true
simarity_name: segment
threshold: true
- matchs: 
target: k510
ptq: true
simarity_name: segment
threshold: true
"""
runner = TfliteTestRunner(request.node.name, overwirte_configs=overwrite_cfg)
```
=> Update Compare method

src/importer/onnx/onnx_importer.cpp, src/importer/onnx/onnx_importer.h, src/importer/onnx/ops/constant.cpp
=> Fix constant input for onnx

include/nncase/ir/op_utils.h, include/nncase/ir/visitor.h, include/nncase/schedule/buffers.h, include/nncase/schedule/scheduler.h, include/nncase/transforms/neutral/optimize_allocation.h, src/ir/visitor.cpp, src/schedule/scheduler.cpp, src/transforms/neutral/optimize_allocation.cpp, tests/schedule/buffer_fusion/test_multi_bitcast_single_concat.py
=> Fix offset issue of bitcast and concat.

src/importer/onnx/ops/batchnorm.cpp, tests/importer/onnx/basic/test_batchnorm.py, tests/importer/onnx/basic/test_conv_add_batchnorm.py, tests/importer/onnx/combine/test_act_load_psum_fuse.py
=> Update batchnorm test cases for onnx.

include/nncase/transforms/neutral/global_reduce_window_to_reduce.h, src/targets/neutral_target.cpp, src/transforms/neutral/global_reduce_window_to_reduce.cpp
=> move reduce_to_global_reduce_window_transform to k510 compiler

include/nncase/transforms/neutral/add_to_conv2d.h, src/transforms/neutral/CMakeLists.txt, src/transforms/neutral/add_to_conv2d.cpp, targets/k210/k210_target.cpp, tests/importer/tflite/model/test_mobilenetv2.py, tests/importer/tflite/model/test_resnet50.py, tests/importer/tflite/model/test_resnet50v2.py
- Convert elementwise Add to Conv2D which may utilize K210 KPU
=> Add kpu add for k210

src/importer/onnx/ops/clip.cpp, tests/importer/onnx/basic/test_clip.py
=> Fix clip empty input and use onnx helper test case.

src/ir/visitor.cpp, src/transforms/neutral/optimize_allocation.cpp, tests/schedule/buffer_fusion/test_concat_like_openpose.py
=> fix concat

src/importer/onnx/ops/batchnorm.cpp
=> fix onnx importer of batchnorm

tests/config.yml, tests/importer/onnx/basic/test_gemm2.py, tests/importer/onnx/basic/test_onehot.py, tests/importer/onnx/basic/test_pool.py, tests/importer/onnx/combine/test_act_load_psum_fuse.py, tests/importer/tflite/basic/test_onehot.py, tests/importer/tflite/model/test_mobilenetv1.py, tests/onnx_test_runner.py
=> Fix test runner.

src/transforms/neutral/transpose_motion.cpp, tests/transform/test_transpose_reduce_motion_transform.py
=> Fix transpose/binary/reduce transform issue.

include/nncase/compiler.h, include/nncase/targets/neutral_target.h, include/nncase/targets/target.h, python/nncase/native/ffi.cpp, src/cli/compile.cpp, src/cli/compile.h, src/evaluator/quantizer.cpp, src/nncase/compiler.cpp, src/targets/neutral_target.cpp, src/targets/target.cpp, targets/k210/k210_target.cpp, targets/k210/k210_target.h
add parameter to specific weights quant type
=> add w_quant_type

.github/workflows/code-format.yml, tools/clang-format.sh
format脚本里写死的 CLANG_FORMAT_LLVM_INSTALL_DIR 去掉啦
=> code format workflow

src/ir/graph.cpp, src/ir/graph.partition.cpp, tests/graph_partition/test_merge_graph.py
=> update graph region merge

include/nncase/transforms/neutral/pre_process_setting.h, src/nncase/compiler.cpp, src/transforms/neutral/pre_process_setting.cpp, tests/config.yml, tests/test_runner.py
=> fix preprocess

src/importer/onnx/ops/activations.cpp, tests/importer/onnx_/basic/test_leakyrelu.py
=> Fix default alpha attribute of LeakyRelu onnx op.

include/nncase/transforms/neutral/binary_motion.h, include/nncase/transforms/neutral/fold_conv2d_binary.h, src/targets/neutral_target.cpp, src/transforms/neutral/CMakeLists.txt, src/transforms/neutral/binary_motion.cpp, src/transforms/neutral/fold_conv2d_binary.cpp
=> Optimize conv+pool+mul+add in resnet50v2

src/importer/onnx/ops/matmul.cpp, tests/importer/onnx_/basic/test_matmul.py
=> Support more input shapes for onnx matmul.

include/nncase/ir/ops/lstm.h, src/importer/onnx/ops/lstm.cpp, src/importer/onnx/ops/matmul.cpp, src/ir/ops/lstm.cpp, src/transforms/neutral/lstm_transform.cpp, tests/importer/onnx_/basic/test_lstm.py
=> [lstm] add y_h y_c output

docs/FAQ_EN.md, docs/FAQ_ZH.md
=> Update FAQ about ops can be accelerated by KPU

src/cli/compile.h, targets/k210/k210_target.cpp, tests/importer/onnx_/basic/test_selu.py
=> Enable selu on k210

.github/workflows/compiler-build.yml, .github/workflows/compiler-python-release.yml, .github/workflows/runtime-win-x64-msvc.yml
=> Upgrade msvc-dev-cmd

include/nncase/ir/ops/lstm.h, include/nncase/runtime/datatypes.h, include/nncase/transforms/neutral/lstm_transform.h, src/importer/caffe/ops/lstm.cpp, src/importer/onnx/ops/lstm.cpp, src/ir/ops/lstm.cpp, src/transforms/neutral/lstm_transform.cpp, tests/importer/onnx_/basic/test_lstm.py
=> Add bidirectional for LSTM.

examples/yolox/k210/yolox_detect_example/main.c, src/Nncase.Core/IR/Imaging/ResizeImage.cs, src/Nncase.Core/TIR/MemRef.cs, src/Nncase.Core/TIR/Script.cs, src/Nncase.Evaluator/Imaging/ResizeImage.cs, src/Nncase.Evaluator/TypeInference.cs, src/Nncase.SourceGenerator/Evaluator/EvaluatorGenerator.cs, src/Nncase.SourceGenerator/Rule/RuleGenerator.cs, src/Nncase.SourceGenerator/Rule/RuleReceiver.cs, src/Nncase.Tests/Core/UnitTestTypeInfer.cs, src/Nncase.Tests/TIR/UnitTestDLLCall.cs, src/nncase/simulator.cpp
1. Fix Native lib support multi inputs
2. Fix ResizeImage Typeinfer 
3. Rule Generator support array/scalar
=> Fix Native & Typeinfer

src/importer/tflite/ops/transpose_conv.cpp, tests/importer/tflite_/basic/test_conv2d_transpose.py
=> fix tflite conv2d_transpose importer

.github/workflows/compiler-build.yml, .github/workflows/compiler-test.yml, conanfile.py, modules/vulkan/src/codegen/templates/template.cpp, tests/config.yml
- Set versions of deps
- Set k210 ptq threshold to 0.97
=> Fix ci failing

src/ir/graph.cpp
keep output order when splitting graph, especially for multi-outputs.
=> keep output order when splitting graph

tests/importer/onnx_/basic/test_reduce.py
=> add onnx ReduceSum

tests/onnx_test_runner.py
- use '10' to instead of '0' in input_shape
=> remove 4D limitation for onnx input shape

src/Nncase.Core/Transform/FunctionPass.cs, src/Nncase.Core/Transform/ModulePass.cs, src/Nncase.Core/Transform/PassManager.cs, src/Nncase.Core/Transform/RulesPass.cs, src/Nncase.Core/Transform/RunPassOptions.cs, src/Nncase.Core/Transform/TIRPass.cs, src/Nncase.EGraph/Transform/EGraphExtractor.cs, src/Nncase.EGraph/Transform/EGraphRewriter.cs, src/Nncase.Graph/Transform/DataFlowRewriter.cs, src/Nncase.Quantization/Quantization/CalibrationEvaluator.cs, src/Nncase.Tests/EGraph/UnitTestEGraph.cs, src/Nncase.Tests/Rewrite/RewriteBase.cs, src/Nncase.Tests/Rewrite/UnitTestEGraphRewrite.cs, src/Nncase.Tests/Rules/Neutral/UnitTestIntegralPromotion.cs, src/Nncase.Tests/Transform/UnitTestSubstitutor.cs, src/Nncase.Transform/Passes/ShapeInferPass.cs
1. remove the pass dump dir
2. optimized Tir pass dump
=> remove pass dump dir

.github/workflows/compiler-build.yml, .gitignore
=> Add coverage

.github/workflows/compiler-build.yml
=> Add integration test coverage

tests/importer/tflite_/basic/test_compare.py
Changed the threshold to a fixed value to reduce type error
=> change compare threshold

src/Nncase.Transform/Rules/Neutral/Fusion.cs
=> update double inputs fusion

src/Nncase.Cli/Commands/Compile.cs, src/Nncase.Compiler/Compiler.cs, src/Nncase.Core/IR/ILDotPrintVisitor.cs, src/Nncase.Tests/Rules/Neutral/UnitTestAddMarker.cs
1. fix cli start bug
2. il dot dump support tuple
3. fix compile run pass api.
=> Fix Cli Start Compiler Bug

src/Nncase.Compiler/Compiler.cs, src/Nncase.Tests/Rewrite/Fusion/IDataFlowFusionCase.cs, src/Nncase.Tests/Rewrite/Fusion/UnitTestFusionGroup.cs, src/Nncase.Transform/Mutators/IFusionMergeRule.cs
=> fix same input merge bug

src/Nncase.Tests/Rewrite/Fusion/IDataFlowFusionCase.cs, src/Nncase.Tests/Rewrite/Fusion/UnitTestFusionGroup.cs, src/Nncase.Transform/Mutators/IFusionMergeRule.cs
=> add shortcut fusion merge

src/Nncase.Evaluator/Math/Quantize.cs, src/Nncase.Tests/Evaluator/UnitTestEvaluatorMath.cs
because of onnxruntime not support quant to i16, add i16 quant evaluator
=> add i16 quant eval

src/Nncase.Evaluator/NN/Activations.cs, src/Nncase.Evaluator/NN/NNModule.cs, src/Nncase.Tests/Quant/UnitTestAddRangeOfMarker.cs, src/Nncase.Transform/Rules/Neutral/AddRangeOfAndMarker.cs
=> relu6 support

src/Nncase.Core/IR/NN/Normalization.cs, src/Nncase.Evaluator/NN/NNModule.cs, src/Nncase.Evaluator/NN/Normalization.cs, src/Nncase.Tests/Evaluator/UnitTestEvaluatorNN.cs, src/Nncase.Tests/Evaluator/UnitTestEvaluatorRandom.cs
=> Add NN and Random evaluator unit test.

src/Nncase.Compiler/Compiler.cs, src/Nncase.Tests/Rules/Neutral/UnitTestCombineTranspose.cs, src/Nncase.Transform/Rules/Neutral/CombineTranspose.cs
constrain condition of CombineTransposeConstBinary and register to TargetIndependentPass.
=> fix CombineTransposeConstBinary

src/Nncase.Tests/Rewrite/Fusion/UnitTestFusionMaker.cs, src/Nncase.Tests/Rewrite/UnitTestDataFlowRewrite.cs, src/Nncase.Transform/Passes/DataflowWithUsdByPass.cs
1. The k230 have some gnne rule need UsdbyInfo, but now gnne rule can't using EgraphRwrite.
2. Added DataflowWithUsdByPass as a temporary solution
=> Add DataflowWithUsdByPass

src/Nncase.Tests/Rules/Neutral/UnitTestCombineTranspose.cs, src/Nncase.Transform/Rules/Neutral/CombineTranspose.cs
fix CombineTransposeConcat and open unit test.
=> fix combine_transpose_concat

.github/workflows/compiler-build.yml, .github/workflows/compiler-python-release.yml, .github/workflows/runtime-build.yml, pyproject.toml, src/runtime/stackvm/runtime_function.cpp, src/runtime/stackvm/runtime_module.cpp, src/runtime/stackvm/runtime_module.h
Reduce data transfer between stackvm and KPU.
=> Allocate stackvm.data with shared pool

python/nncase/__init__.py, python/nncase/native/ffi.cpp, src/Native/include/nncase/compiler.h, src/Nncase.Compiler/Compiler.cs
supplement dump_flags of python interface
=> update python dump_flags

src/Nncase.Core/TensorUtilities.cs, src/Nncase.Core/Utf8Char.cs, src/Nncase.Tests/Core/UnitTestTensor.cs, src/Nncase.Tests/Core/UnitTestTensorConversions.cs, src/Nncase.Tests/Core/UnitTestTensorHelper.cs, src/Nncase.Tests/Core/UnitTestTensorOfT.Helper.cs, src/Nncase.Tests/Core/UnitTestTensorOfT.cs, src/Nncase.Tests/Core/UnitTestTensorUtilities.cs, src/Nncase.Tests/Core/UnitTestUtf8Char.cs
=> Add unit test for Nncase.core.Tensor/Tensor<T>.

src/Nncase.Core/PatternMatch/PatternUtility.cs
1. add useful parameter in the IsSIFusionPattern.
=> Fix IsSIFusionPattern

modules/Nncase.Modules.K210/Targets/K210Target.cs, modules/Nncase.Modules.StackVM/Targets/CPUTarget.cs, src/Nncase.Cli/Commands/Compile.cs, src/Nncase.Compiler/Compiler.cs, src/Nncase.Core/CompilerServices.cs, src/Nncase.Core/CostModel/Cost.cs, src/Nncase.Core/IR/CSharpPrintVisitor.cs, src/Nncase.Core/IR/IIRPrinterProvider.cs, src/Nncase.Core/IR/IRPrinterProvider.cs, src/Nncase.Core/ITarget.cs, src/Nncase.Core/TensorOfT.cs, src/Nncase.EGraph/Transform/EGraphExtractor.cs, src/Nncase.Evaluator/CostEvaluateVisitor.cs, src/Nncase.Evaluator/NN/Activations.cs, src/Nncase.Evaluator/NN/Conv2D.cs, src/Nncase.Evaluator/TypeInference.cs, src/Nncase.Tests.TestFixture/TransformBase/TestVisitor.cs, src/Nncase.Tests/Core/UnitTestTypeInfer.cs, src/Nncase.Tests/CostModel/UnitTestEGraphCostModel.cs, src/Nncase.Tests/Diagnostics/UnitTestDumpper.cs
1. Add csharp dumper randConst mode. when randConst == false, will save the constant into bin file.
2. Add RegisterTargetInDependentPass in ITarget 
3. Fix Conv2D/Activation cost compute
=> add csharp dumper randconst

src/Nncase.Compiler/Compiler.cs, src/Nncase.Passes/Rules/Neutral/FlattenToReshape.cs, src/Nncase.Tests/Rules/Neutral/UnitTestFlattenToReshape.cs
=> add flatten to reshape

src/Nncase.Importer/Onnx/OnnxImporter.cs, src/Nncase.Importer/Onnx/Upsample.cs, tests/importer/onnx_/basic/test_upsample.py
1. add importer for upsample
2. add pytest
=> add importer of onnx upsample

src/Native/src/runtime/stackvm/evaluate_stack.cpp, src/Nncase.Core/IR/Tensors/Functional.cs, src/Nncase.Evaluator/NN/Conv2DTranspose.cs, src/Nncase.Importer/Onnx/Conv2DTranspose.cs, src/Nncase.Importer/TFLite/Conv2DTranspose.cs, src/Nncase.Tests/Evaluator/UnitTestEvaluatorNN.cs, tests/importer/onnx_/basic/test_conv_transpose.py, tests/importer/tflite_/basic/test_conv2d_transpose.py
1. fix tflite deconv importer
2. fix onnx deconv importer
3. fix deconv evaulator
4. add related pytests
=> fix conv2d transpose

src/Nncase.Core/IR/Expr.cs
=> Fix IsDescendantOf

src/Nncase.Importer/TFLite/Conv2DTranspose.cs, tests/importer/tflite_/basic/test_conv2d_transpose.py
- fix tflite deconv importer
- change pytest to keras
=> fix tflite deconv importer

modules/Nncase.Modules.StackVM/Targets/CPUTarget.cs, src/Nncase.Compiler/Compiler.cs, src/Nncase.Core/ITarget.cs
add RegisterTargetDependentBeforeCodeGen
=> Add new stage

tests/onnx_test_runner.py, tests/test_runner.py
1. pytest infer output shape for dynamic model, avoid set var for output dim
2. fix dynamic model become static after simplification
=> pytest output infer

src/Native/include/nncase/runtime/simple_types.h, src/Native/include/nncase/runtime/util.h, src/Native/include/nncase/shape.h, src/Native/src/kernels/stackvm/tensor_ops.cpp, tests/importer/onnx_/basic/test_constantofshape.py, tests/test_runner.py
1. extend dims_t and strides_t to capacity 8
2. constrain optimized concat
=> support concat more than 4d

src/Native/src/kernels/stackvm/shape_infer.h, src/Nncase.Importer/Onnx/MatMul.cs, tests/importer/onnx_/basic/test_matmul.py
=> update matmul importer

modules/Nncase.Modules.StackVM/packages.lock.json, src/Nncase.Cli/packages.lock.json, src/Nncase.Compiler/packages.lock.json, src/Nncase.EGraph/packages.lock.json, src/Nncase.Evaluator/packages.lock.json, src/Nncase.Graph/packages.lock.json, src/Nncase.Passes/packages.lock.json, src/Nncase.Quantization/packages.lock.json, src/Nncase.Tests.TestFixture/packages.lock.json, src/Nncase.Tests/packages.lock.json
=> Fix Ci Code Format

src/Nncase.Passes/Rules/Neutral/FoldReduces.cs, src/Nncase.Tests/Rules/Neutral/UnitTestFoldReduces.cs
=> fold reduce

python/nncase/__init__.py, tests/config.yml
=> fix python script preprocess

src/Nncase.EGraph/Passes/EGraphExtractors/SatExtractor.cs
1. parallel solve
2. add max solve time
=> Add parallel solve

src/Nncase.EGraph/Passes/EGraphExtractors/SatExtractor.cs
=> fix sat extractor

tests/evaluator.py, tests/inference.py
if outputlayout is empty, output result will not be transposed
=> fix output result transpose

src/Nncase.EGraph/Passes/EGraphExtractors/SatExtractor.cs
1. increase solver search time
2. add env var `SOLVE_MAX_TIME` config max time.
=> GNNE-1714 fix sat solver on resnet50

python/_nncase.pyi, python/nncase/__init__.py, python/nncase/native/ffi.cpp, src/Native/include/nncase/compiler.h, src/Nncase.Importer/Onnx/MatMul.cs, src/Nncase.Importer/Onnx/OnnxImporter.cs, tests/config.yml, tests/evaluator.py, tests/inference.py, tests/onnx_test_runner.py
1. fix pytest onnx with seperated data
2. fix matmul importer
3. add importer of LogicalOr
=> GNNE-1882 Fix/llm-debug

src/Native/src/kernels/stackvm/optimized/riscv64/unary.cpp, src/Native/src/kernels/stackvm/reference/batch_to_space.cpp, src/Native/src/kernels/stackvm/reference/pad.cpp, src/Native/src/kernels/stackvm/reference/space_to_batch.cpp, src/Nncase.Core/IR/Tensors/Functional.cs, src/Nncase.Core/IR/Util.cs, src/Nncase.Evaluator/NN/BatchToSpace.cs, src/Nncase.Evaluator/NN/SpaceToBatch.cs, src/Nncase.Evaluator/Tensors/Where.cs, src/Nncase.Importer/Onnx/Conv2DTranspose.cs, src/Nncase.Importer/TFLite/Conv2DTranspose.cs, src/Nncase.Importer/TFLite/TFLiteImporter.cs, src/Nncase.Importer/TFLite/Tile.cs, src/Nncase.Passes/Rules/Neutral/CombineReshape.cs, src/Nncase.Passes/Rules/Neutral/CombineTranspose.cs, src/Nncase.Tests/Evaluator/UnitTestShapeEvaluator.cs
=> GNNE-1891 Fix Dynamic TTS

python/nncase/__init__.py, src/Nncase.Passes/Rules/ShapeBucket/ShapeBucket.cs, tests/config.toml, tests/inference.py
fix python interface for shape bucket
=> fix python interface

src/Native/src/kernels/stackvm/tensor_ops.cpp
fix bucket pad when sizeof(input.dtype) != 4
=> Fix BucketPad

src/Native/src/kernels/stackvm/tensor_ops.cpp
=> Fix GetItem

src/Native/src/kernels/stackvm/optimized/slice.cpp, src/Nncase.Importer/Onnx/Binary.cs, src/Nncase.Importer/Onnx/Split.cs, src/Nncase.Importer/Onnx/Transpose.cs, src/Nncase.Passes/Rules/Neutral/SqueezeShape.cs
1,Modify the slice module to support five dimensions;
2,Supplement the metadata information of some OPs to derive a complete quantification scheme.
=> GNNE-1714:Fix/fix transform about quant

src/Nncase.Passes/Rules/Neutral/BatchNormToBinary.cs, src/Nncase.Passes/Rules/Neutral/CombineTranspose.cs, src/Nncase.Passes/Rules/Neutral/SqueezeShape.cs
1,add missing meta information for quant
=> GNNE-1714:add missing meta information for quant

src/Nncase.EGraph/Passes/EGraphExtractors/SatExtractor.cs, src/Nncase.Passes/Rules/Neutral/FoldBinary.cs
1, Supports configuring the number of processors using macro definitions;
2, Upgrade FoldNopBinary to support tensor form.
=> GNNE-1714:Fix/some opt

CMakeLists.txt, src/Native/include/nncase/ntt/detail/shape_storage.h, src/Native/include/nncase/ntt/kernels/binary.h, src/Native/include/nncase/ntt/shape.h, src/Native/include/nncase/ntt/tensor.h, src/Native/include/nncase/ntt/utility.h
Optimized branches:
- Contiguous dims
- Non broadcast
- Left/Right broadcast
=> Optimize fixed binary

src/Nncase.Compiler/Compiler.cs, src/Nncase.Core/TIR/Script.cs, src/Nncase.Core/TensorUtilities.cs, src/Nncase.Evaluator/EvaluateVisitor.cs, src/Nncase.Importer/Onnx/DataGatter.cs, src/Nncase.Passes/BufferSchedule/BufferScheduleTypes.cs, src/Nncase.Passes/BufferSchedule/BufferScheduler.cs, src/Nncase.Passes/BufferSchedule/LifeTimeCollector.cs, src/Nncase.Passes/Rules/Neutral/PowOf2ToSquare.cs
1. fix single tensor of onnx that larger than 2GB
2. remove constrain of fusion eval
3. power of 2 to square
=> fix externel data

conanfile.py, python/common/runtime_tensor.inl, tests/kernels/CMakeLists.txt, tests/kernels/kernel_test.h, tests/kernels/macro_util.h, tests/kernels/test_prelu.cpp
=> fix numpy non contiguous

src/Native/include/nncase/ntt/arch/x86_64/ukernels.h, src/Native/include/nncase/ntt/detail/shape_storage.h, src/Native/include/nncase/ntt/kernels/matmul.h, src/Native/include/nncase/ntt/primitive_ops.h, src/Native/include/nncase/ntt/shape.h, src/Native/include/nncase/ntt/shape_infer/matmul.h, src/Native/include/nncase/ntt/tensor.h, src/Native/include/nncase/ntt/ukernels.h, src/Native/include/nncase/ntt/utility.h, src/Native/test/benchmark_test/benchmark_ntt_clamp.cpp
=> [NTT] Add ukernel for matmul

modules/Nncase.Modules.CPU/CodeGen/CPU/FunctionBuilder.cs, modules/Nncase.Modules.CPU/Evaluator/CPU/Pack.cs, modules/Nncase.Modules.CPU/Passes/Rules/CPU/PackRule.cs, modules/Nncase.Modules.StackVM/CodeGen/StackVM/CodegenVisitor.cs, src/Nncase.Core/ITensorInitializer.cs, src/Nncase.Core/Tensor.cs, src/Nncase.Core/TensorOfT.cs, src/Nncase.Core/Utilities/SpanUtility.cs, src/Nncase.EGraph/Passes/RewriteProvider.cs, src/Nncase.Evaluator/Extension/OrtKIExtensions.cs, src/Nncase.Importer/Onnx/DataGatter.cs, src/Nncase.Passes/DDrBufferSchdeulePass.cs, src/Nncase.Passes/Rules/Lower/QuantizerMatmul.cs, src/Nncase.Schedule/Schedule/TileGraph/PrimGraphSolveResult.cs
1. fix matmul quaantize
2. fix single tensor exceeds 2GB using tensor<T>
3. optimize copy of matmul tiling
=> fix bugs found in xpu debugging

modules/Nncase.Modules.CPU/Targets/CPUTarget.cs, src/Nncase.Core/Utilities/ShapeExprUtility.cs, src/Nncase.Importer/HuggingFace/HuggingFaceImporter.cs, src/Nncase.Importer/HuggingFace/Qwen2.cs, tests/generator.py, tests/huggingface_test_runner.py, tests/test_runner.py
1. 将输入除input_id 外都暂时去掉（可选参数）
2. 修改错误，当前已经将而已和huggingface的推理（fp32 模式）可以对上，见截图
=> [fix]: fix huggingface-Qwen2 result not correct

src/Nncase.Core/IR/Dimension.cs, src/Nncase.Core/IR/Tensors/Functional.cs, src/Nncase.Diagnostics/Diagnostics/ILPrintVisitor.cs, src/Nncase.Evaluator/Tensors/Reshape.cs, src/Nncase.Evaluator/Tensors/Tile.cs, src/Nncase.Importer/Onnx/DataGatter.cs, src/Nncase.Importer/Onnx/GetAttribute.cs, src/Nncase.Importer/Onnx/Slice.cs, src/Nncase.Importer/Onnx/Softmax.cs, src/Nncase.Importer/Onnx/Transpose.cs, src/Nncase.Tests/Evaluator/UnitTestEvaluatorTensors.cs, src/Nncase.Tests/Rewrite/UnitTestDataFlowRewrite.cs
- Return unranked shape when input is unranked in typeinfer of Tile/Reshape
- Return unknown dim when input is unknown dim in Dimension arithmetics
- Add some UTs
=> Fix typeinfer of Tile/Reshape when input is unranked

modules/Nncase.Modules.NTT/CodeGen/CPU/KernelCSourceConvertVisitor.cs, ntt/include/nncase/ntt/kernels/get_position_ids.h, src/Nncase.Evaluator/NN/GetPositionIds.cs
=> fix get_position_ids

modules/Nncase.Modules.NTT/CodeGen/CPU/DeviceCSourceConvertVisitor.cs, modules/Nncase.Modules.NTT/CodeGen/CPU/KernelCSourceConvertVisitor.cs, modules/Nncase.Modules.NTT/CodeGen/CPU/Templates/Kernels/PackedLayerNorm.cshtml, modules/Nncase.Modules.NTT/Evaluator/TIR/CPU/PackedLayerNorm.cs, modules/Nncase.Modules.NTT/Passes/AffineSelection/LayerNorm.cs, modules/Nncase.Modules.NTT/Passes/AffineSelection/MatMul.cs, modules/Nncase.Modules.NTT/Passes/NTTAffineSelectionPass.cs, modules/Nncase.Modules.NTT/Passes/NTTTIRSelectionPass.cs, modules/Nncase.Modules.NTT/Passes/Rules/NTT/PackRule.cs, ntt/include/nncase/ntt/kernels/layer_norm.h, ntt/include/nncase/ntt/shape.h, src/Native/src/test.cpp, src/Native/src/test_cli.cpp, src/Nncase.Core/TIR/Script.cs, src/Nncase.Core/TensorUtilities.cs, src/Nncase.Core/Utilities/DistributedUtility.cs, src/Nncase.Core/Utilities/ISLUtility.cs, src/Nncase.Evaluator/TypeInferenceVisitor.cs, src/Nncase.Schedule/Schedule/GraphTiler.cs, src/Nncase.Schedule/Schedule/TileGraph/GraphMCTS.cs, src/Nncase.Schedule/Schedule/TileGraph/PrimGraphSolveResult.cs, src/Nncase.Schedule/Transforms/AutoTilePass.cs, src/Nncase.Tests/Affine/UnitTestAffine.cs, src/Nncase.Tests/Affine/UnitTestTileGraph.cs, src/Nncase.Tests/Targets/UnitTestCPUKernels.cs
=> [feat] Support XPU tiling

modules/Nncase.Modules.NTT/CodeGen/CPU/DeviceCSourceConvertVisitor.cs, modules/Nncase.Modules.NTT/CodeGen/CPU/KernelCSourceConvertVisitor.cs, modules/Nncase.Modules.NTT/Evaluator/TIR/CPU/CPUModule.cs, modules/Nncase.Modules.NTT/Evaluator/TIR/CPU/RoPE.cs, modules/Nncase.Modules.NTT/Passes/AffineSelection/RoPE.cs, modules/Nncase.Modules.NTT/Passes/NTTAffineSelectionPass.cs, modules/Nncase.Modules.NTT/Passes/NTTTIRSelectionPass.cs, modules/Nncase.Modules.NTT/Passes/Rules/NTT/Vectorize/VectorizeRoPE.cs, modules/Nncase.Modules.NTT/TIR/NTT/Functional.cs, modules/Nncase.Modules.NTT/TIR/NTT/RoPE.cs, modules/Nncase.Modules.NTT/Targets/CPUTarget.cs, ntt/include/nncase/ntt/kernels/rope.h, ntt/include/nncase/ntt/ntt.h, src/Nncase.Core/IR/NN/Functional.cs, src/Nncase.Core/IR/NN/RoPE.cs, src/Nncase.Evaluator/NN/NNModule.cs, src/Nncase.Evaluator/NN/RoPE.cs, src/Nncase.Importer/HuggingFace/HuggingFaceBaseModel.cs
=> [feat] RoPE
